### PR TITLE
Handle failure gracefully

### LINKED ISSUE #234: Error in idOcrVerification: TypeError: Cannot read properties of undefined (reading 'words')
### Describe the bug

- Error in idOcrVerification: TypeError: Cannot read properties of undefined (reading 'words')

### To Reproduce
- When verification fails, data property doesn't exist.
- First check the response and only decrypt

### Expected behavior

- Please check the [response](https://github.com/ninetydays/kross-SDK/blob/931dcb0ff80d16abc3c311513a28289fbd5fc0d8/src/kross-client/verifications.ts#L65C1-L66C1) if success then only decrypt the data

### PR DESCRIPTION
**Pull request by Jscripter-pk**
closes #234

### CODE REVIEW

File: src/kross-client/verifications.ts [hunk 1]
```diff
@@ -62,18 +62,27 @@ export class Verifications extends KrossClientBase {
         }
       );
 
-      const data: string = response.data.data as unknown as string;
```
Comment (aziyatali) [inline src/kross-client/verifications.ts:65]: @Jscripter-pk  Would not it be better to check 
`if (response.data.success)`
